import React, { useState } from 'react';
import axios from 'axios';
import { Slider } from '@/components/ui/slider';
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, Label } from 'recharts';
import { Skeleton } from '@/components/ui/skeleton';
import InfoTooltip from './InfoTooltip';

export default function ContaminationSlider({ runId, initialContamination, distribution, onRecalculate }) {
  const [val, setVal] = useState(() => {
    const safeC = initialContamination === 'auto' ? 0.05 : parseFloat(initialContamination);
    return isNaN(safeC) ? 0.05 : safeC;
  });
  const [loading, setLoading] = useState(false);

  const handleApply = async () => {
    if (!runId) return;
    setLoading(true);
    try {
      const res = await axios.post(`http://localhost:8000/rerun-analysis?run_id=${runId}&contamination=${val}`);
      onRecalculate(res.data);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="w-full">
      <h3 className="font-semibold text-lg text-text-primary mb-2 flex items-center">
        Isolation Score Distribution
        <InfoTooltip text="Histogram of anomaly scores generated by the Isolation Forest model. The X-axis represents the isolation score, and the Y-axis is the frequency. Use the slider to set the contamination threshold." />
      </h3>
      
      {loading ? (
        <div className="w-full h-[250px] flex items-center justify-center">
          <Skeleton className="w-full h-full rounded-xl bg-card-border/50" />
        </div>
      ) : (
        <>
          {distribution && distribution.length > 0 && (
            <div className="h-[220px] w-full mb-6">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={distribution} margin={{ top: 10, right: 10, bottom: 15, left: -10 }}>
                  <XAxis dataKey="score" stroke="var(--text-secondary)" fontSize={11} tickCount={10} tickFormatter={t => parseFloat(t).toFixed(2)}>
                    <Label value="Isolation Score (Lower is closer to Anomalous)" offset={-5} position="insideBottom" fill="var(--text-secondary)" fontSize={11} />
                  </XAxis>
                  <YAxis stroke="var(--text-secondary)" fontSize={11}>
                     <Label value="Count" angle={-90} position="insideLeft" fill="var(--text-secondary)" fontSize={11} />
                  </YAxis>
                  <Tooltip 
                    contentStyle={{ backgroundColor: 'var(--tooltip-bg)', border: '1px solid var(--card-border)', color: 'var(--text-primary)' }} 
                    itemStyle={{ color: 'var(--text-primary)' }}
                    cursor={{fill: 'var(--card-border)'}}
                  />
                  <Bar dataKey="count" fill="var(--text-secondary)" radius={[2, 2, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
            </div>
          )}

          <div className="flex flex-col gap-3 mt-4 px-2">
            <div className="flex justify-between items-center text-sm">
              <span className="text-text-secondary">Expected Contamination Threshold: <strong className="text-accent ml-1">{(val || 0.05).toFixed(3)}</strong></span>
              <button 
                onClick={handleApply}
                disabled={loading}
                className="bg-accent text-[#0D1117] hover:bg-accent/90 px-4 py-1.5 rounded-md transition-colors font-semibold cursor-pointer"
              >
                Apply Re-calculation
              </button>
            </div>
            <Slider 
              value={[val]} 
              min={0.01} 
              max={0.20} 
              step={0.005} 
              onValueChange={(v) => { if (v && v.length) setVal(v[0]) }} 
              className="mt-2"
            />
          </div>
        </>
      )}
    </div>
  );
}
